### ISSUE TITLE
unable to apply custom background to the picker

### ISSUE THREAD

**Issue by NarendraSingh88** [budiadiono/react-native-custom-picker#1]
I tried applying the below style, but doesn't seem working

```
  popupDisabledInputStyleForDropdown: {
    marginRight: 20,

    marginTop: 5,
    paddingLeft: 15,
    paddingRight: 10,
    paddingTop: 6,
    paddingBottom: 6,
    backgroundColor: "#252446",
    borderColor: "#92A4D5",
    borderRadius: 8,
    alignSelf: "flex-end",

    borderWidth: 1
  }
```
Please, let me know how to make it work.

Neither, I am getting any way to make it work with `TouchableOpacity` :(

**Comment by budiadiono** [comment]
I've just release a new version - [0.2.0](https://github.com/budiadiono/react-native-custom-picker/releases/tag/v0.2.0) which include new capability to styling the component.  You may want to take a look [this example](https://github.com/budiadiono/react-native-custom-picker/blob/master/example/src/screens/styling.js).

Hope it can help you to resolve this issue. I'll close this issue, feel free to re-open if it's still persist.
