### ISSUE TITLE
How to set default item

### ISSUE THREAD

**Issue by nimamyscreen** [budiadiono/react-native-custom-picker#2]

**Comment by budiadiono** [comment]
You can use `value` props.

```
<CustomPicker
  options={['One', 'Two', 'Three', 'Four', 'Five']}
  value="Two"
/>
```

**Comment by budiadiono** [comment]
After while, I was thinking that you meant about the **default item** is the item that would be set as a **selected item** when clear button get pressed.

So in this new version - [0.2.0](https://github.com/budiadiono/react-native-custom-picker/releases/tag/v0.2.0) I've added new prop called `defaultValue` which works like that. You may want to take a look at [this example](https://github.com/budiadiono/react-native-custom-picker/blob/master/example/src/screens/defaultValue.js)

Hope it can help you to resolve this issue. I'll close this issue, feel free to re-open if it's still persist.
