### ISSUE TITLE
Need to double tap an item to select

### ISSUE THREAD

**Issue by kachnitel** [budiadiono/react-native-custom-picker#3]
Hello!
I'm trying to implement the picker in a modal with an adjacent TextInput and noticed that if I tap the text first (or autoFocus), I have to double tap the item to select.

I've gone and changed [the ScrollView](https://github.com/budiadiono/react-native-custom-picker/blob/69e93106f2f4ca3903748baace6527000d7f3dbd/src/index.tsx#L115) adding `keyboardShouldPersistTaps={'handled'}` and all works as expected.

Being in TS I'll have to do some more learning if you'd like me to submit a PR, but I've tested it in the "compiled" code and it fixes that issue, perhaps it could be optional if there's drawbacks? I imagine the prop could just be passed from the root component if that's the case.

**Comment by kachnitel** [comment]
I may have not done enough testing as now it appears as if `keyboardShouldPersistTaps={'handled'}` on the CustomPicker itself fixes it. If that's the expected behavior, maybe it would be a good idea to link to [the RN issue](https://github.com/facebook/react-native/issues/4087) or some hint about this?

**Comment by budiadiono** [comment]
Hi @kachnitel,

Thanks for this good catch! I'm sorry for this super late response -- I think I can add a new props --something like `scrollViewProps` and pass it to [ScrollView](https://github.com/budiadiono/react-native-custom-picker/blob/69e93106f2f4ca3903748baace6527000d7f3dbd/src/index.tsx#L115), so we can control the ScrollView behavior.
