### ISSUE TITLE
How to open the modal programmatically?

### ISSUE THREAD

**Issue by Lixus** [budiadiono/react-native-custom-picker#7]
Does this component have a function to open the modal? Like `inputComponent.focus()` for the TextInput component. This would be very useful for guiding the user through a form like this: `onSubmitEditing={() => {this.inputPicker.open();}}`. Thanks!

**Comment by budiadiono** [comment]
Hi @Lixus,

I'm sorry for super late response.

You can use `showOptions` method (https://github.com/budiadiono/react-native-custom-picker/blob/master/src/index.tsx#L171) to do this. 

For example:

```js
import * as React from 'react';
import { Alert, Button, View } from 'react-native';
import { CustomPicker } from 'react-native-custom-picker';

export default class App extends React.Component {
  render() {
    const options = ['One', 'Two', 'Three', 'Four', 'Five'];
    let picker
    return (
      <View
        style={{ flex: 1, flexDirection: 'column', justifyContent: 'center' }}>
        <Button title="Open" onPress={()=>{
          if (picker) {
            picker.showOptions();
          }
        }} />
        <CustomPicker
          ref={el=>picker = el}
          options={options}
          onValueChange={value => {
            Alert.alert('Selected Item', value || 'No item were selected!');
          }}
        />        
      </View>
    );
  }
}
```

Here's the demo: https://snack.expo.io/@budiadiono/react-native-custom-picker-open-modal

**Comment by Lixus** [comment]
Thanks!
